require "pkg-config"
require "native-package-installer"

task :default => "dependency:check"

namespace :dependency do
  desc "Check dependency"
  task :check do
    unless PKGConfig.check_version?("dlib-glib")
      unless NativePackageInstaller.install(:debian => "libdlib-glib-dev",
                                            :redhat => "dlib-glib-devel")
        exit(false)
      end
    end
  end
end
